# Generated by Django 5.0.6 on 2024-06-04 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_grounds', '0002_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 8, 6, 42, 251364)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_content',
            field=models.TextField(),
        ),
    ]
