# Generated by Django 5.0.6 on 2024-06-05 15:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_grounds', '0003_blog_pub_date_alter_blog_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 8, 5, 39, 175188)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('pub_date', models.DateField(default=datetime.datetime(2024, 6, 5, 8, 5, 39, 175331))),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_grounds.blog')),
            ],
        ),
    ]
