# Generated by Django 5.0.6 on 2024-06-05 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_grounds', '0005_alter_blog_pub_date_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 15, 9, 34, 942952, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 15, 9, 34, 943239, tzinfo=datetime.timezone.utc)),
        ),
    ]
