# Generated by Django 5.0.6 on 2024-06-11 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_grounds', '0013_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testing_grounds.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_content',
            field=models.CharField(max_length=200),
        ),
    ]
